import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import { CERTIFICATION_CATALOG } from "../lib/certifications";
import { calculateCertificateDates } from "../lib/certificate-dates";
import { database } from "./postgres";

const TEMPLATE_COLORS: Record<string, [string, string]> = {
  "9001": ["#3b54a5", "#cb131e"],
  "14001": ["#183d35", "#286c43"],
  "18001": ["#3c2745", "#81476f"],
  "22000": ["#493427", "#8b582e"],
  "27001": ["#1d3150", "#3d6092"],
  GMP: ["#3a2d49", "#72518b"],
  HACCP: ["#4b302d", "#994a3e"],
  CE: ["#253b48", "#38758c"],
  ROHS: ["#31423a", "#537647"],
  GREEN: ["#244334", "#417c3e"],
  "13485": ["#1d4050", "#267388"],
  SA8000: ["#433247", "#804d75"],
  "45001": ["#3f3424", "#906323"],
  "20001": ["#24374c", "#426597"],
  "17024": ["#3e2f47", "#745788"],
};

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS enquiries (
    id TEXT PRIMARY KEY NOT NULL,
    company_name TEXT NOT NULL,
    address TEXT NOT NULL,
    scope TEXT NOT NULL,
    contact_person TEXT NOT NULL,
    mobile TEXT NOT NULL,
    email TEXT NOT NULL,
    certification TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'enquiry',
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_enquiries_status_created
    ON enquiries(status, created_at)`,
  `CREATE TABLE IF NOT EXISTS certifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    certificate_prefix TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_certifications_code
    ON certifications(code)`,
  `CREATE TABLE IF NOT EXISTS companies (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    contact_person TEXT NOT NULL,
    mobile TEXT NOT NULL,
    email TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS certificates (
    id TEXT PRIMARY KEY NOT NULL,
    company_id TEXT NOT NULL,
    certification_id INTEGER NOT NULL,
    scope TEXT NOT NULL,
    certificate_number TEXT,
    status TEXT NOT NULL DEFAULT 'draft_created',
    draft_date TEXT,
    approval_date TEXT,
    issue_date TEXT,
    first_surveillance_date TEXT,
    second_surveillance_date TEXT,
    third_surveillance_date TEXT,
    expiry_date TEXT,
    printed_at TEXT,
    application_checked INTEGER NOT NULL DEFAULT 0,
    legal_checked INTEGER NOT NULL DEFAULT 0,
    continuity_checked INTEGER NOT NULL DEFAULT 0,
    documentation_checked INTEGER NOT NULL DEFAULT 0,
    draft_sent_at TEXT,
    created_at TEXT NOT NULL,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (certification_id) REFERENCES certifications(id)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_certificates_number
    ON certificates(certificate_number)`,
  `CREATE INDEX IF NOT EXISTS idx_certificates_status
    ON certificates(status)`,
  `CREATE INDEX IF NOT EXISTS idx_certificates_expiry
    ON certificates(expiry_date)`,
  `CREATE TABLE IF NOT EXISTS certificate_counters (
    counter_key TEXT PRIMARY KEY NOT NULL,
    last_value INTEGER NOT NULL DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS certificate_legacy (
    certificate_id TEXT PRIMARY KEY NOT NULL,
    source_sheet TEXT NOT NULL,
    source_row INTEGER NOT NULL,
    associate_name TEXT,
    original_standard TEXT,
    legacy_certificate_number TEXT,
    printed INTEGER NOT NULL DEFAULT 0,
    delivered INTEGER NOT NULL DEFAULT 0,
    activated INTEGER NOT NULL DEFAULT 0,
    application_date TEXT,
    FOREIGN KEY (certificate_id) REFERENCES certificates(id)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_certificate_legacy_source
    ON certificate_legacy(source_sheet, source_row)`,
  `CREATE TABLE IF NOT EXISTS certificate_settings (
    id INTEGER PRIMARY KEY NOT NULL CHECK (id = 1),
    brand_name TEXT NOT NULL,
    office_address TEXT NOT NULL,
    registration_heading TEXT NOT NULL,
    intro_wording TEXT NOT NULL,
    conformity_wording TEXT NOT NULL,
    footer_wording TEXT NOT NULL,
    signatory_name TEXT,
    signatory_title TEXT NOT NULL,
    logo_key TEXT,
    signature_key TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS certificate_templates (
    standard_code TEXT PRIMARY KEY NOT NULL,
    standard_label TEXT NOT NULL,
    heading TEXT NOT NULL,
    opening_text TEXT NOT NULL,
    conformity_text TEXT NOT NULL,
    scope_heading TEXT NOT NULL,
    clarification_text TEXT NOT NULL,
    footer_text TEXT NOT NULL,
    primary_color TEXT NOT NULL,
    accent_color TEXT NOT NULL,
    standard_logo_key TEXT,
    accreditation_logo_key TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS certificate_assets (
    asset_key TEXT PRIMARY KEY NOT NULL,
    content_type TEXT NOT NULL,
    body BYTEA NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS admin_users (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL CHECK (role IN ('admin', 'operator', 'reviewer', 'viewer')),
    password_hash TEXT NOT NULL,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS admin_sessions (
    token_hash TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_admin_sessions_user ON admin_sessions(user_id)`,
];

export type EnquiryRecord = {
  id: string;
  company_name: string;
  address: string;
  scope: string;
  contact_person: string;
  mobile: string;
  email: string;
  certification: string;
  notes: string | null;
  status: string;
  created_at: string;
};

export type CertificationRecord = {
  id: number;
  name: string;
  code: string;
  certificate_prefix: string;
};

export type CertificateRecord = {
  id: string;
  company_id: string;
  company_name: string;
  address: string;
  contact_person: string;
  mobile: string;
  email: string | null;
  certification_name: string;
  certification_code: string;
  certificate_prefix: string;
  scope: string;
  certificate_number: string | null;
  status: string;
  draft_date: string | null;
  approval_date: string | null;
  issue_date: string | null;
  first_surveillance_date: string | null;
  second_surveillance_date: string | null;
  third_surveillance_date: string | null;
  expiry_date: string | null;
  printed_at: string | null;
  application_checked: number;
  legal_checked: number;
  continuity_checked: number;
  documentation_checked: number;
  draft_sent_at: string | null;
  created_at: string;
  legacy_source_row: number | null;
  legacy_certificate_number: string | null;
  original_standard: string | null;
  associate_name: string | null;
};

export type CertificateSettings = {
  brand_name: string;
  office_address: string;
  registration_heading: string;
  intro_wording: string;
  conformity_wording: string;
  footer_wording: string;
  signatory_name: string | null;
  signatory_title: string;
  logo_key: string | null;
  signature_key: string | null;
  updated_at: string;
};

export type CertificateDesignTemplate = {
  standard_code: string;
  standard_label: string;
  heading: string;
  opening_text: string;
  conformity_text: string;
  scope_heading: string;
  clarification_text: string;
  footer_text: string;
  primary_color: string;
  accent_color: string;
  standard_logo_key: string | null;
  accreditation_logo_key: string | null;
  updated_at: string;
};

export type LegacyRecord = {
  source_sheet: string;
  source_row: number;
  certificate_id: string;
  company_id: string;
  company_name: string;
  address: string;
  scope: string;
  contact_person: string;
  mobile: string;
  email: string | null;
  associate_name: string;
  standard_code: string;
  standard_name: string;
  certificate_prefix: string;
  original_standard: string;
  certificate_number: string | null;
  legacy_certificate_number: string | null;
  status: string;
  printed: boolean;
  delivered: boolean;
  activated: boolean;
  application_date: string | null;
  draft_date: string | null;
  issue_date: string | null;
  first_surveillance_date: string | null;
  second_surveillance_date: string | null;
  third_surveillance_date: string | null;
  expiry_date: string | null;
};

let databaseReady = false;

export async function ensureDatabase() {
  if (databaseReady) return;
  try {
    await initializeDatabase();
    databaseReady = true;
  } catch (error) {
    console.error("[database] Failed to initialize PostgreSQL schema.", error);
    throw error;
  }
}

async function initializeDatabase() {
  await database.batch(schemaStatements.map((sql) => database.prepare(sql)));
  for (const column of ["application_checked", "legal_checked", "continuity_checked", "documentation_checked"]) {
    await database.prepare(`ALTER TABLE certificates ADD COLUMN IF NOT EXISTS ${column} INTEGER NOT NULL DEFAULT 0`).run();
  }
  await database.prepare(`ALTER TABLE certificates ADD COLUMN IF NOT EXISTS draft_sent_at TEXT`).run();
  await database.batch(
    CERTIFICATION_CATALOG.map(({ name, code, prefix }) =>
      database.prepare(
        `INSERT INTO certifications (name, code, certificate_prefix, active)
         VALUES (?, ?, ?, 1)
         ON CONFLICT(code) DO NOTHING`,
      ).bind(name, code, prefix),
    ),
  );
  await database.prepare(`UPDATE certifications SET active = 0 WHERE code = 'OTHER'`).run();
  await database.batch(CERTIFICATION_CATALOG.map(({ code, name }) => database.prepare(
    `INSERT INTO certificate_templates
      (standard_code, standard_label, heading, opening_text, conformity_text, scope_heading,
       clarification_text, footer_text, primary_color, accent_color, updated_at)
     VALUES (?, ?, 'Certificate of Registration', 'This is to certify that the management system of',
       'has been assessed and found to conform to the requirements of', 'Scope of certification',
       'Further clarification of this certificate and its scope may be obtained from the certified organization.',
       'This certificate remains the property of Prudential ISO and is subject to certification terms and conditions.',
       ?, ?, ?)
     ON CONFLICT (standard_code) DO NOTHING`,
  ).bind(code, name, ...(TEMPLATE_COLORS[code] ?? TEMPLATE_COLORS["9001"]), new Date().toISOString())));
  await database.prepare(`UPDATE certificate_templates
    SET primary_color = '#3b54a5', accent_color = '#cb131e'
    WHERE standard_code = '9001' AND primary_color = '#123547' AND accent_color = '#08766f'`).run();
  await database.prepare(
    `INSERT OR IGNORE INTO certificate_settings
      (id, brand_name, office_address, registration_heading, intro_wording,
       conformity_wording, footer_wording, signatory_name, signatory_title, updated_at)
     VALUES (1, 'Prudential ISO', '1&1A, UR Nagar Extn, Anna Nagar W Ext St, Chennai, Tamil Nadu 600101', 'Certificate of Registration',
       'This is to certify that the management system of',
       'has been assessed and found to conform to the requirements of',
       'This certificate remains the property of Prudential ISO and is subject to the certification terms and conditions.',
       NULL, 'Authorized Signatory', ?)`,
  ).bind(new Date().toISOString()).run();
}

export async function createEnquiry(input: Omit<EnquiryRecord, "id" | "status" | "created_at">) {
  await ensureDatabase();
  const id = crypto.randomUUID();
  await database.prepare(
    `INSERT INTO enquiries
      (id, company_name, address, scope, contact_person, mobile, email, certification, notes, status, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'enquiry', ?)`,
  ).bind(
    id, input.company_name, input.address, input.scope, input.contact_person,
    input.mobile, input.email, input.certification, input.notes,
    new Date().toISOString(),
  ).run();
  return id;
}

export async function listEnquiries() {
  await ensureDatabase();
  const result = await database.prepare(
    `SELECT * FROM enquiries ORDER BY created_at DESC LIMIT 100`,
  ).all<EnquiryRecord>();
  return result.results;
}

export async function getEnquiry(id: string) {
  await ensureDatabase();
  return database.prepare(`SELECT * FROM enquiries WHERE id = ? LIMIT 1`)
    .bind(id).first<EnquiryRecord>();
}

export async function updateEnquiry(id: string, input: Omit<EnquiryRecord, "id" | "status" | "created_at">) {
  await ensureDatabase();
  const result = await database.prepare(
    `UPDATE enquiries SET
      company_name = ?, address = ?, scope = ?, contact_person = ?,
      mobile = ?, email = ?, certification = ?, notes = ?
     WHERE id = ?`,
  ).bind(
    input.company_name, input.address, input.scope, input.contact_person,
    input.mobile, input.email, input.certification, input.notes, id,
  ).run();
  if (!result.meta.changes) throw new Error("Enquiry not found.");
}

export async function listCertifications() {
  await ensureDatabase();
  const result = await database.prepare(
    `SELECT id, name, code, certificate_prefix
     FROM certifications WHERE active = 1
     ORDER BY CASE code
       ${CERTIFICATION_CATALOG.map((item, index) => `WHEN '${item.code}' THEN ${index}`).join(" ")}
       ELSE ${CERTIFICATION_CATALOG.length}
     END, name ASC`,
  ).all<CertificationRecord>();
  return result.results;
}

export async function createStandardTemplate(input: {
  code: string; name: string; certificatePrefix: string;
  primaryColor: string; accentColor: string;
}) {
  await ensureDatabase();
  const code = input.code.trim().toUpperCase();
  const name = input.name.trim();
  const prefix = input.certificatePrefix.trim().toUpperCase();
  if (!/^[A-Z0-9][A-Z0-9._-]{1,23}$/.test(code) ||
      !name || name.length > 120 ||
      !/^[A-Z0-9]{2,12}$/.test(prefix) ||
      !/^#[0-9A-Fa-f]{6}$/.test(input.primaryColor) ||
      !/^#[0-9A-Fa-f]{6}$/.test(input.accentColor)) {
    throw new Error("Enter a valid standard name, code, certificate prefix, and colors.");
  }
  const existing = await database.prepare(`SELECT id FROM certifications WHERE code = ?`)
    .bind(code).first<{ id: number }>();
  if (existing) throw new Error("A standard with this code already exists.");
  const now = new Date().toISOString();
  await database.batch([
    database.prepare(`INSERT INTO certifications (name, code, certificate_prefix, active) VALUES (?, ?, ?, 1)`)
      .bind(name, code, prefix),
    database.prepare(`INSERT INTO certificate_templates
      (standard_code, standard_label, heading, opening_text, conformity_text, scope_heading,
       clarification_text, footer_text, primary_color, accent_color, updated_at)
     VALUES (?, ?, 'Certificate of Registration', 'This is to certify that the management system of',
       'has been assessed and found to conform to the requirements of', 'Scope of certification',
       'Further clarification of this certificate and its scope may be obtained from the certified organization.',
       'This certificate remains the property of Prudential ISO and is subject to certification terms and conditions.',
       ?, ?, ?)`).bind(code, name, input.primaryColor, input.accentColor, now),
  ]);
  return code;
}

export type NewCertificateInput = {
  companyName: string; address: string; scope: string; email: string;
  mobile: string; contactPerson: string; certificationIds: number[];
  applicationChecked: boolean; legalChecked: boolean;
  continuityChecked: boolean; documentationChecked: boolean;
  enquiryId?: string;
};

export async function createCertificates(input: NewCertificateInput) {
  await ensureDatabase();
  if (![input.applicationChecked, input.legalChecked, input.continuityChecked, input.documentationChecked].every(Boolean)) {
    throw new Error("Confirm all four document checklist items before creating certificate records.");
  }
  const ids = [...new Set(input.certificationIds)];
  if (!input.companyName.trim() || !input.address.trim() || !input.scope.trim() ||
      !input.email.trim() || !input.mobile.trim() || !input.contactPerson.trim() ||
      !input.email.includes("@") || !ids.length || ids.some((id) => !Number.isInteger(id))) {
    throw new Error("Complete the company information and select at least one standard.");
  }
  const available = await listCertifications();
  if (ids.some((id) => !available.some((item) => item.id === id))) throw new Error("Invalid standard.");
  const companyId = crypto.randomUUID();
  const certificateIds = ids.map(() => crypto.randomUUID());
  const now = new Date().toISOString();
  const checklist = [input.applicationChecked, input.legalChecked, input.continuityChecked, input.documentationChecked].map(Number);
  const statements = [
    database.prepare(
      `INSERT INTO companies
        (id, name, address, contact_person, mobile, email, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
    ).bind(
      companyId, input.companyName.trim(), input.address.trim(), input.contactPerson.trim(),
      input.mobile.trim(), input.email.trim(), now,
    ),
    ...ids.map((certificationId, index) => database.prepare(
      `INSERT INTO certificates
        (id, company_id, certification_id, scope, status, created_at,
         application_checked, legal_checked, continuity_checked, documentation_checked)
       VALUES (?, ?, ?, ?, 'draft_created', ?, ?, ?, ?, ?)`,
    ).bind(certificateIds[index], companyId, certificationId, input.scope.trim(), now, ...checklist)),
  ];
  if (input.enquiryId) statements.push(database.prepare(`UPDATE enquiries SET status = 'converted' WHERE id = ?`).bind(input.enquiryId));
  await database.batch(statements);
  return certificateIds[0];
}

export async function createCertificateFromEnquiry(enquiryId: string, certificationIds: number[], checklist: Pick<NewCertificateInput,
  "applicationChecked" | "legalChecked" | "continuityChecked" | "documentationChecked">) {
  const enquiry = await getEnquiry(enquiryId);
  if (!enquiry || enquiry.status === "converted") throw new Error("Enquiry is unavailable.");
  return createCertificates({
    companyName: enquiry.company_name, address: enquiry.address, scope: enquiry.scope,
    email: enquiry.email, mobile: enquiry.mobile, contactPerson: enquiry.contact_person,
    certificationIds, ...checklist, enquiryId,
  });
}

export async function listCertificates(options: { query?: string; filter?: "review" | "issued" } = {}) {
  await ensureDatabase();
  const conditions: string[] = [];
  const bindings: string[] = [];
  const query = options.query?.trim();
  if (query) {
    conditions.push(`(UPPER(company.name) LIKE UPPER(?) OR UPPER(COALESCE(cert.certificate_number, legacy.legacy_certificate_number, '')) LIKE UPPER(?))`);
    bindings.push(`%${query}%`, `%${query}%`);
  }
  if (options.filter === "review") conditions.push(`cert.certificate_number IS NULL AND legacy.certificate_id IS NOT NULL`);
  if (options.filter === "issued") conditions.push(`cert.certificate_number IS NOT NULL`);
  const where = conditions.length ? ` WHERE ${conditions.join(" AND ")}` : "";
  const prepared = database.prepare(
    `${certificateSelectSql}${where} ORDER BY cert.created_at DESC LIMIT 300`,
  );
  const result = bindings.length
    ? await prepared.bind(...bindings).all<CertificateRecord>()
    : await prepared.all<CertificateRecord>();
  return result.results;
}

export async function getCertificate(id: string) {
  await ensureDatabase();
  return database.prepare(`${certificateSelectSql} WHERE cert.id = ? LIMIT 1`)
    .bind(id).first<CertificateRecord>();
}

export async function listCompanyCertificates(companyId: string) {
  await ensureDatabase();
  const result = await database.prepare(`${certificateSelectSql} WHERE cert.company_id = ? ORDER BY standard.name`)
    .bind(companyId).all<CertificateRecord>();
  return result.results;
}

export async function findCertificateByNumber(certificateNumber: string) {
  await ensureDatabase();
  return database.prepare(
    `${certificateSelectSql} WHERE UPPER(cert.certificate_number) = UPPER(?) LIMIT 1`,
  ).bind(certificateNumber).first<CertificateRecord>();
}

export async function setCertificateStatus(id: string, action: string, issueDate?: string, checklist?: boolean[]) {
  await ensureDatabase();
  const certificate = await getCertificate(id);
  if (!certificate) throw new Error("Certificate not found.");
  if (action === "checklist") {
    if (certificate.certificate_number || !["draft_created", "changes_requested"].includes(certificate.status) || !checklist || checklist.length !== 4) throw new Error("Checklist cannot be updated.");
    await database.prepare(`UPDATE certificates SET application_checked = ?, legal_checked = ?, continuity_checked = ?, documentation_checked = ? WHERE id = ?`)
      .bind(...checklist.map(Number), id).run();
    return;
  }
  if (action === "draft") {
    if (certificate.status !== "draft_created" && certificate.status !== "changes_requested") throw new Error("Draft cannot be marked now.");
    if (![certificate.application_checked, certificate.legal_checked, certificate.continuity_checked, certificate.documentation_checked].every(Boolean)) {
      throw new Error("Complete the document checklist first.");
    }
    await database.prepare(`UPDATE certificates SET status = 'draft_created', draft_date = ? WHERE id = ?`)
      .bind(new Date().toISOString().slice(0, 10), id).run();
    return;
  }
  if (action === "waiting_approval") {
    if (!certificate.draft_date || !["draft_created", "changes_requested"].includes(certificate.status)) throw new Error("Mark the draft first.");
    if (![certificate.application_checked, certificate.legal_checked, certificate.continuity_checked, certificate.documentation_checked].every(Boolean)) throw new Error("Complete the document checklist first.");
    await database.prepare(`UPDATE certificates SET status = 'waiting_approval', draft_sent_at = ? WHERE id = ?`).bind(new Date().toISOString(), id).run();
    return;
  }
  if (action === "changes_requested") {
    if (certificate.status !== "waiting_approval") throw new Error("Draft is not awaiting confirmation.");
    await database.prepare(`UPDATE certificates SET status = 'changes_requested' WHERE id = ?`).bind(id).run();
    return;
  }
  if (action === "approve") {
    if (certificate.status !== "waiting_approval") throw new Error("Draft is not awaiting confirmation.");
    await database.prepare(
      `UPDATE certificates SET status = 'approved', approval_date = ? WHERE id = ?`,
    ).bind(new Date().toISOString().slice(0, 10), id).run();
    return;
  }
  if (action === "print" && certificate.status === "issued") {
    const settings = await getCertificateSettings();
    if (!settings.signature_key) throw new Error("Upload a signature before final printing.");
    await database.prepare(
      `UPDATE certificates SET status = 'printed', printed_at = ? WHERE id = ? AND certificate_number IS NOT NULL`,
    ).bind(new Date().toISOString(), id).run();
    return;
  }
  if (action !== "print" || !issueDate || certificate.status !== "approved" || certificate.certificate_number) throw new Error("Unsupported certificate action.");
  const settings = await getCertificateSettings();
  if (!settings.signature_key) throw new Error("Upload a signature before final printing.");

  const dates = calculateCertificateDates(issueDate);
  const yy = issueDate.slice(2, 4);
  const mm = issueDate.slice(5, 7);
  const usesGlobalSequence = certificate.certification_code === "20001" || certificate.certification_code === "17024";
  const numberStem = usesGlobalSequence
    ? certificate.certificate_prefix
    : `${certificate.certificate_prefix}${yy}${mm}`;
  const sequenceLength = usesGlobalSequence ? 9 : 4;
  const counterKey = `certificate-number:${numberStem}`;
  const existing = await database.prepare(
    `SELECT COALESCE(MAX(CAST(SUBSTR(certificate_number, ?) AS INTEGER)), 0) AS last_value
     FROM certificates
     WHERE certificate_number LIKE ? AND LENGTH(certificate_number) = ?`,
  ).bind(numberStem.length + 1, `${numberStem}%`, numberStem.length + sequenceLength)
    .first<{ last_value: number }>();

  await database.prepare(
    `INSERT INTO certificate_counters (counter_key, last_value) VALUES (?, ?)
     ON CONFLICT(counter_key) DO UPDATE SET
       last_value = MAX(certificate_counters.last_value, excluded.last_value)`,
  ).bind(counterKey, existing?.last_value ?? 0).run();

  const counter = await database.prepare(
    `UPDATE certificate_counters
     SET last_value = last_value + 1
     WHERE counter_key = ?
     RETURNING last_value`,
  ).bind(counterKey).first<{ last_value: number }>();
  if (!counter) throw new Error("Certificate number could not be generated.");
  if (counter.last_value > 10 ** sequenceLength - 1) {
    throw new Error("The certificate number sequence has reached its limit.");
  }

  const number = `${numberStem}${String(counter.last_value).padStart(sequenceLength, "0")}`;
  await database.prepare(
    `UPDATE certificates SET
      status = 'printed', certificate_number = ?, issue_date = ?, printed_at = ?,
      first_surveillance_date = ?, second_surveillance_date = ?,
      third_surveillance_date = ?, expiry_date = ?
     WHERE id = ? AND status = 'approved' AND certificate_number IS NULL`,
  ).bind(
    number, dates.issueDate, new Date().toISOString(), dates.firstSurveillanceDate, dates.secondSurveillanceDate,
    null, dates.expiryDate, id,
  ).run();
}

export async function getCertificateSettings() {
  await ensureDatabase();
  const settings = await database.prepare(
    `SELECT brand_name, office_address, registration_heading, intro_wording,
      conformity_wording, footer_wording, signatory_name, signatory_title,
      logo_key, signature_key, updated_at
     FROM certificate_settings WHERE id = 1`,
  ).first<CertificateSettings>();
  if (!settings) throw new Error("Certificate settings are unavailable.");
  return settings;
}

export async function listCertificateDesignTemplates() {
  await ensureDatabase();
  const rows = await database.prepare(`SELECT * FROM certificate_templates ORDER BY standard_code`).all<CertificateDesignTemplate>();
  return rows.results;
}

export async function getCertificateDesignTemplate(code: string) {
  await ensureDatabase();
  return database.prepare(`SELECT * FROM certificate_templates WHERE standard_code = ? LIMIT 1`)
    .bind(code).first<CertificateDesignTemplate>();
}

export async function updateCertificateDesignTemplate(code: string, input: Pick<CertificateDesignTemplate,
  "standard_label" | "heading" | "opening_text" | "conformity_text" | "scope_heading" |
  "clarification_text" | "footer_text" | "primary_color" | "accent_color">) {
  await ensureDatabase();
  const result = await database.batch([
    database.prepare(`UPDATE certificate_templates SET standard_label = ?, heading = ?,
    opening_text = ?, conformity_text = ?, scope_heading = ?, clarification_text = ?, footer_text = ?,
    primary_color = ?, accent_color = ?, updated_at = ? WHERE standard_code = ?`)
    .bind(input.standard_label, input.heading, input.opening_text, input.conformity_text,
      input.scope_heading, input.clarification_text, input.footer_text, input.primary_color,
      input.accent_color, new Date().toISOString(), code),
    database.prepare(`UPDATE certifications SET name = ? WHERE code = ?`)
      .bind(input.standard_label, code),
  ]);
  if (!result[0].count) throw new Error("Certificate template not found.");
}

export async function putTemplateAsset(code: string, kind: "standard" | "accreditation", file: File) {
  if (!await getCertificateDesignTemplate(code)) throw new Error("Certificate template not found.");
  const extension = file.type === "image/png" ? "png" : file.type === "image/jpeg" ? "jpg" : "webp";
  const key = `certificate/templates/${code}/${kind}-${crypto.randomUUID()}.${extension}`;
  await putStoredAsset(key, file);
  const column = kind === "standard" ? "standard_logo_key" : "accreditation_logo_key";
  await database.prepare(`UPDATE certificate_templates SET ${column} = ?, updated_at = ? WHERE standard_code = ?`)
    .bind(key, new Date().toISOString(), code).run();
}

export async function getTemplateAsset(code: string, kind: "standard" | "accreditation") {
  const template = await getCertificateDesignTemplate(code);
  const key = kind === "standard" ? template?.standard_logo_key : template?.accreditation_logo_key;
  if (!key) return null;
  const stored = await getStoredAsset(key);
  if (stored) return stored;
  try {
    const filePath = assetPath(key);
    const [body, details] = await Promise.all([readFile(filePath), stat(filePath)]);
    return { body, contentType: contentTypeForKey(key), etag: `"${details.size}-${Math.trunc(details.mtimeMs)}"` };
  } catch (error) {
    if (["ENOENT", "EPERM"].includes((error as NodeJS.ErrnoException).code ?? "")) return null;
    throw error;
  }
}

export async function updateCertificateSettings(input: Omit<CertificateSettings, "logo_key" | "signature_key" | "updated_at">) {
  await ensureDatabase();
  await database.prepare(
    `UPDATE certificate_settings SET
      brand_name = ?, office_address = ?, registration_heading = ?,
      intro_wording = ?, conformity_wording = ?, footer_wording = ?,
      signatory_name = ?, signatory_title = ?, updated_at = ?
     WHERE id = 1`,
  ).bind(
    input.brand_name, input.office_address, input.registration_heading,
    input.intro_wording, input.conformity_wording, input.footer_wording,
    input.signatory_name, input.signatory_title, new Date().toISOString(),
  ).run();
}

export async function putCertificateAsset(kind: "logo" | "signature", file: File) {
  await ensureDatabase();
  const extension = file.type === "image/png" ? "png" : file.type === "image/jpeg" ? "jpg" : "webp";
  const key = `certificate/${kind}-${crypto.randomUUID()}.${extension}`;
  await putStoredAsset(key, file);
  const column = kind === "logo" ? "logo_key" : "signature_key";
  await database.prepare(
    `UPDATE certificate_settings SET ${column} = ?, updated_at = ? WHERE id = 1`,
  ).bind(key, new Date().toISOString()).run();
}

export async function getCertificateAsset(kind: "logo" | "signature") {
  const settings = await getCertificateSettings();
  const key = kind === "logo" ? settings.logo_key : settings.signature_key;
  if (!key) return null;
  const stored = await getStoredAsset(key);
  if (stored) return stored;
  const filePath = assetPath(key);
  try {
    const [body, details] = await Promise.all([readFile(filePath), stat(filePath)]);
    return {
      body,
      contentType: contentTypeForKey(key),
      etag: `"${details.size}-${Math.trunc(details.mtimeMs)}"`,
    };
  } catch (error) {
    if (["ENOENT", "EPERM"].includes((error as NodeJS.ErrnoException).code ?? "")) return null;
    throw error;
  }
}

export async function importLegacyCertificates(records: LegacyRecord[]) {
  await ensureDatabase();
  const existing = await database.prepare(
    `SELECT COUNT(*) AS count FROM certificate_legacy`,
  ).first<{ count: number }>();

  let imported = 0;
  for (let start = 0; start < records.length; start += 20) {
    const chunk = records.slice(start, start + 20);
    const statements = [];
    for (const record of chunk) {
      statements.push(
        database.prepare(
          `INSERT OR IGNORE INTO certifications
            (name, code, certificate_prefix, active) VALUES (?, ?, ?, 1)`,
        ).bind(record.standard_name, record.standard_code, record.certificate_prefix),
        database.prepare(
          `INSERT OR IGNORE INTO companies
            (id, name, address, contact_person, mobile, email, created_at)
           VALUES (?, ?, ?, ?, ?, ?, ?)`,
        ).bind(
          record.company_id, record.company_name, record.address,
          record.contact_person || "Not recorded", record.mobile || "Not recorded",
          record.email, new Date().toISOString(),
        ),
        database.prepare(
          `INSERT OR IGNORE INTO certificates
            (id, company_id, certification_id, scope, certificate_number, status,
             draft_date, issue_date, first_surveillance_date, second_surveillance_date,
             third_surveillance_date, expiry_date, created_at)
           SELECT ?, ?, id, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
           FROM certifications WHERE code = ?`,
        ).bind(
          record.certificate_id, record.company_id, record.scope,
          record.certificate_number, record.status, record.draft_date,
          record.issue_date, record.first_surveillance_date,
          record.second_surveillance_date, record.third_surveillance_date,
          record.expiry_date, new Date().toISOString(), record.standard_code,
        ),
        database.prepare(
          `INSERT OR IGNORE INTO certificate_legacy
            (certificate_id, source_sheet, source_row, associate_name,
             original_standard, legacy_certificate_number, printed, delivered,
             activated, application_date)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        ).bind(
          record.certificate_id, record.source_sheet, record.source_row,
          record.associate_name || null, record.original_standard || null,
          record.legacy_certificate_number, record.printed ? 1 : 0,
          record.delivered ? 1 : 0, record.activated ? 1 : 0,
          record.application_date,
        ),
      );
    }
    await database.batch(statements);
    imported += chunk.length;
  }

  const after = await database.prepare(
    `SELECT COUNT(*) AS count FROM certificate_legacy`,
  ).first<{ count: number }>();
  return {
    processed: imported,
    added: Number(after?.count ?? 0) - Number(existing?.count ?? 0),
    total: Number(after?.count ?? 0),
  };
}

export async function getLegacyImportStats() {
  await ensureDatabase();
  const [records, review, companies] = await Promise.all([
    count(`SELECT COUNT(*) AS count FROM certificate_legacy`),
    count(`SELECT COUNT(*) AS count FROM certificate_legacy legacy
      JOIN certificates cert ON cert.id = legacy.certificate_id
      WHERE cert.certificate_number IS NULL`),
    count(`SELECT COUNT(DISTINCT company_id) AS count FROM certificates cert
      JOIN certificate_legacy legacy ON legacy.certificate_id = cert.id`),
  ]);
  return { records, review, companies };
}

export async function getDashboardCounts() {
  await ensureDatabase();
  const [enquiries, waiting, issued, printing] = await Promise.all([
    count(`SELECT COUNT(*) AS count FROM enquiries WHERE status = 'enquiry'`),
    count(`SELECT COUNT(*) AS count FROM certificates WHERE status = 'waiting_approval'`),
    count(`SELECT COUNT(*) AS count FROM certificates WHERE status IN ('issued', 'printed') AND substr(issue_date, 1, 7) = ?`, new Date().toISOString().slice(0, 7)),
    count(`SELECT COUNT(*) AS count FROM certificates WHERE status = 'approved'`),
  ]);
  return { enquiries, waiting, issued, printing };
}

async function count(sql: string, parameter?: string) {
  const query = database.prepare(sql);
  const row = parameter
    ? await query.bind(parameter).first<{ count: number }>()
    : await query.first<{ count: number }>();
  return Number(row?.count ?? 0);
}

async function putStoredAsset(key: string, file: File) {
  await database.prepare(`INSERT INTO certificate_assets (asset_key, content_type, body, updated_at)
    VALUES (?, ?, ?, ?)`).bind(key, file.type, new Uint8Array(await file.arrayBuffer()), new Date().toISOString()).run();
}

async function getStoredAsset(key: string) {
  const row = await database.prepare(`SELECT content_type, body, updated_at FROM certificate_assets WHERE asset_key = ?`)
    .bind(key).first<{ content_type: string; body: Uint8Array; updated_at: string }>();
  if (!row) return null;
  return { body: row.body, contentType: row.content_type, etag: `"${row.body.length}-${row.updated_at}"` };
}

function assetPath(key: string) {
  const root = process.env.ASSET_STORAGE_PATH ||
    (process.env.NODE_ENV === "production" ? "/data/assets" : path.join(process.cwd(), ".local-assets"));
  return path.join(root, ...key.split("/").filter(Boolean));
}

function contentTypeForKey(key: string) {
  if (key.endsWith(".png")) return "image/png";
  if (key.endsWith(".jpg") || key.endsWith(".jpeg")) return "image/jpeg";
  return "image/webp";
}

const certificateSelectSql = `
  SELECT cert.*, company.name AS company_name, company.address,
    company.contact_person, company.mobile, company.email,
    standard.name AS certification_name, standard.code AS certification_code,
    standard.certificate_prefix, legacy.source_row AS legacy_source_row,
    legacy.legacy_certificate_number, legacy.original_standard,
    legacy.associate_name
  FROM certificates cert
  JOIN companies company ON company.id = cert.company_id
  JOIN certifications standard ON standard.id = cert.certification_id
  LEFT JOIN certificate_legacy legacy ON legacy.certificate_id = cert.id
`;
