import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, ClipboardCheck, SearchCheck, ShieldCheck } from "lucide-react";
import { MarketingCta, MarketingShell, SectionHeading, StandardCard } from "@/components/marketing-blocks";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PUBLIC_CERTIFICATION_MAP, PUBLIC_CERTIFICATIONS } from "@/lib/public-certifications";

type CertificationPageProps = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return PUBLIC_CERTIFICATIONS.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: CertificationPageProps): Promise<Metadata> { const item = PUBLIC_CERTIFICATION_MAP.get((await params).slug); return item ? { title: item.title, description: `${item.purpose} Learn the benefits, focus areas, readiness evidence and certification pathway.`, alternates: { canonical: `/certifications/${item.slug}` } } : { title: "Certification guide" }; }

export default async function CertificationPage({ params }: CertificationPageProps) {
  const item = PUBLIC_CERTIFICATION_MAP.get((await params).slug);
  if (!item) return <main className="min-h-screen bg-[#f7f9f8]"><SiteHeader /><MarketingShell className="py-28"><h1 className="font-serif text-5xl text-[#0d2a3d]">Certification guide not found</h1><Button asChild className="mt-8"><Link href="/certifications">Return to the certification directory</Link></Button></MarketingShell><SiteFooter /></main>;
  const related = item.related.flatMap((slug) => { const match = PUBLIC_CERTIFICATION_MAP.get(slug); return match ? [match] : []; });
  const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "Service", name: item.title, serviceType: item.code, description: item.purpose, url: `https://prudentialiso.com/certifications/${item.slug}`, provider: { "@type": "Organization", name: "Prudential ISO", url: "https://prudentialiso.com" } }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://prudentialiso.com/" }, { "@type": "ListItem", position: 2, name: "Certifications", item: "https://prudentialiso.com/certifications" }, { "@type": "ListItem", position: 3, name: item.code, item: `https://prudentialiso.com/certifications/${item.slug}` }] }] };

  return <main className="min-h-screen bg-[#f7f9f8] text-[#18303d]">
    <SiteHeader />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replaceAll("<", "\\u003c") }} />
    <header className="border-b border-[#dce6e4] bg-[radial-gradient(circle_at_80%_10%,#dff4ef_0,transparent_35%),linear-gradient(180deg,#fff_0%,#f4f8f7_100%)]">
      <MarketingShell className="py-10 sm:py-16"><nav className="mb-12 flex items-center gap-2 text-sm font-medium text-[#70838a]" aria-label="Breadcrumb"><Link className="hover:text-[#0f887b]" href="/certifications">Certifications</Link><span>/</span><span>{item.code}</span></nav><div className="grid gap-12 lg:grid-cols-[1fr_330px] lg:items-end"><div><Badge>{item.category}</Badge><h1 className="mt-6 max-w-5xl text-balance font-serif text-5xl font-medium leading-[.98] tracking-[-.05em] text-[#0d2a3d] sm:text-6xl lg:text-7xl">{item.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#566e77]">{item.purpose}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg"><Link href={`/enquire?certification=${encodeURIComponent(item.code)}`}>Request this certification <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline"><Link href="/verify"><SearchCheck /> Verify a certificate</Link></Button></div></div><Card className="rounded-2xl border-[#c7dbd8] shadow-[0_18px_55px_rgba(13,42,61,.09)]"><CardHeader className="border-0"><div><CardDescription>Standard reference</CardDescription><CardTitle className="mt-3 text-3xl">{item.code}</CardTitle></div><ShieldCheck className="size-7 text-[#0f9a8b]" /></CardHeader><CardContent className="pt-0"><div className="rounded-xl bg-[#eff7f5] p-4 text-sm leading-6 text-[#567078]">{item.status === "transition" ? "Withdrawn standard and migration guidance" : "Certification and readiness guide"}</div></CardContent></Card></div></MarketingShell>
    </header>

    <section className="py-20 sm:py-28"><MarketingShell className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><SectionHeading eyebrow="What it is" title="A management decision—not only a certificate." /><div><p className="text-lg leading-9 text-[#526c76]">{item.summary}</p><Card className="mt-8 rounded-2xl border-[#abd4ce] bg-[#ebf7f4] shadow-none"><CardContent className="p-7 font-serif text-2xl leading-9 text-[#0d2a3d]">{item.outcome}</CardContent></Card></div></MarketingShell></section>

    <section className="border-y border-[#dbe5e3] bg-white py-20 sm:py-28"><MarketingShell><SectionHeading eyebrow="Business value" title="What a well-used system can improve" /><div className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{item.benefits.map((benefit, index) => <Card className="rounded-2xl border-[#d9e4e2] shadow-none" key={benefit}><CardContent className="p-6"><span className="grid size-9 place-items-center rounded-lg bg-[#e7f5f2] font-serif text-sm text-[#0f887b]">{String(index + 1).padStart(2, "0")}</span><p className="mt-8 text-base font-medium leading-7 text-[#304b57]">{benefit}</p></CardContent></Card>)}</div></MarketingShell></section>

    <section className="py-20 sm:py-28"><MarketingShell className="grid gap-6 lg:grid-cols-2"><Card className="rounded-3xl border-[#d7e3e2] shadow-none"><CardHeader className="border-0 pb-2"><div><Badge variant="outline">Who it suits</Badge><CardTitle className="mt-5 text-4xl">Designed around operating context, not company size.</CardTitle></div></CardHeader><CardContent><ul className="grid gap-3">{item.suitableFor.map((value) => <li className="flex items-start gap-3 rounded-xl bg-[#f3f7f6] p-4 text-sm leading-6 text-[#435d67]" key={value}><Check className="mt-0.5 size-4 shrink-0 text-[#0f9a8b]" />{value}</li>)}</ul></CardContent></Card><Card className="rounded-3xl border-[#d7e3e2] shadow-none"><CardHeader className="border-0 pb-2"><div><Badge variant="outline">Assessment focus</Badge><CardTitle className="mt-5 text-4xl">What the system needs to control.</CardTitle></div></CardHeader><CardContent><ol className="grid gap-3">{item.focusAreas.map((value, index) => <li className="flex items-start gap-3 rounded-xl bg-[#f3f7f6] p-4 text-sm leading-6 text-[#435d67]" key={value}><span className="font-serif text-[#0f887b]">{String(index + 1).padStart(2, "0")}</span>{value}</li>)}</ol></CardContent></Card></MarketingShell></section>

    <section className="border-y border-[#cfe0dd] bg-[#eaf4f2] py-20 sm:py-28"><MarketingShell className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><span className="grid size-12 place-items-center rounded-2xl bg-white text-[#0f887b] shadow-sm"><ClipboardCheck className="size-6" /></span><div className="mt-6"><SectionHeading eyebrow="Readiness evidence" title="Before requesting assessment" description="This is a practical starting list, not a substitute for the applicable standard or scheme rules." /></div></div><div className="grid gap-4 sm:grid-cols-2">{item.readiness.map((value) => <Card className="rounded-2xl border-white bg-white/90 shadow-none" key={value}><CardContent className="flex gap-3 p-5"><Check className="mt-0.5 size-5 shrink-0 text-[#0f9a8b]" /><span className="text-sm leading-6 text-[#435d67]">{value}</span></CardContent></Card>)}</div></MarketingShell></section>

    <section className="py-20 sm:py-28"><MarketingShell><SectionHeading eyebrow="Certification pathway" title="From defined scope to maintained certificate" /><ol className="mt-12 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[["01","Application and scope","Confirm the organization, sites, activities and standard to be assessed."],["02","Readiness and assessment","Review documented arrangements and evidence that the system operates in practice."],["03","Decision and issue","Close applicable findings before an independent certification decision and issue."],["04","Surveillance and renewal","Maintain the system, complete surveillance activities and renew within the certification cycle."]].map(([number,title,text]) => <li key={number}><Card className="h-full rounded-2xl border-[#d9e4e2] shadow-none"><CardContent className="p-6"><Badge variant="outline">Step {number}</Badge><h3 className="mt-8 font-serif text-2xl font-medium text-[#0d2a3d]">{title}</h3><p className="mt-3 text-sm leading-7 text-[#637982]">{text}</p></CardContent></Card></li>)}</ol></MarketingShell></section>

    {related.length ? <section className="border-y border-[#dbe5e3] bg-white py-20 sm:py-24"><MarketingShell><SectionHeading eyebrow="Related guides" title="Standards often work together." /><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{related.map((relatedItem) => <StandardCard item={relatedItem} compact key={relatedItem.slug} />)}</div></MarketingShell></section> : null}
    <MarketingCta eyebrow="Define your certification record" title="Tell us what your organization does and what the certificate should cover." description="A clear scope helps align the standard, assessment and final certificate record from the beginning." primaryHref={`/enquire?certification=${encodeURIComponent(item.code)}`} primaryLabel="Start enquiry" secondaryHref="/certifications" secondaryLabel="Compare other standards" />
    <SiteFooter />
  </main>;
}
