import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, ClipboardCheck, SearchCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { PUBLIC_CERTIFICATION_MAP, PUBLIC_CERTIFICATIONS } from "@/lib/public-certifications";

type CertificationPageProps = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return PUBLIC_CERTIFICATIONS.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: CertificationPageProps): Promise<Metadata> { const item = PUBLIC_CERTIFICATION_MAP.get((await params).slug); return item ? { title: item.title, description: `${item.purpose} Learn the benefits, focus areas, readiness evidence and certification pathway.`, alternates: { canonical: `/certifications/${item.slug}` } } : { title: "Certification guide" }; }

export default async function CertificationPage({ params }: CertificationPageProps) {
  const item = PUBLIC_CERTIFICATION_MAP.get((await params).slug);
  if (!item) return <main className="guide-site"><SiteHeader /><section className="guide-shell missing-guide"><h1>Certification guide not found</h1><Link href="/certifications">Return to the certification directory</Link></section><SiteFooter /></main>;
  const related = item.related.flatMap((slug) => { const match = PUBLIC_CERTIFICATION_MAP.get(slug); return match ? [match] : []; });
  const structuredData = { "@context": "https://schema.org", "@graph": [{ "@type": "Service", name: item.title, serviceType: item.code, description: item.purpose, url: `https://prudentialiso.com/certifications/${item.slug}`, provider: { "@type": "Organization", name: "Prudential ISO", url: "https://prudentialiso.com" } }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://prudentialiso.com/" }, { "@type": "ListItem", position: 2, name: "Certifications", item: "https://prudentialiso.com/certifications" }, { "@type": "ListItem", position: 3, name: item.code, item: `https://prudentialiso.com/certifications/${item.slug}` }] }] };
  return <main className={`guide-site certification-page accent-${item.accent}`}><SiteHeader />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replaceAll("<", "\\u003c") }} />
    <header className="certification-hero"><div className="guide-shell certification-hero-grid"><div><nav className="guide-breadcrumb" aria-label="Breadcrumb"><Link href="/certifications">Certifications</Link><span>/</span><span>{item.code}</span></nav><p className="guide-kicker">{item.category}</p><h1>{item.title}</h1><p>{item.purpose}</p><div className="guide-actions"><Button asChild size="lg"><Link href={`/enquire?certification=${encodeURIComponent(item.code)}`}>Request this certification <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline"><Link href="/verify"><SearchCheck /> Verify a certificate</Link></Button></div></div><aside><span>Standard reference</span><strong>{item.code}</strong><p>{item.status === "transition" ? "Withdrawn standard / migration guidance" : "Certification and readiness guide"}</p></aside></div></header>
    <section className="certification-summary guide-shell"><div><p className="guide-kicker">What it is</p><h2>A management decision—not only a certificate.</h2></div><div><p>{item.summary}</p><blockquote>{item.outcome}</blockquote></div></section>
    <section className="certification-band"><div className="guide-shell"><div className="certification-section-head"><p className="guide-kicker">Business value</p><h2>What a well-used system can improve</h2></div><div className="benefit-grid">{item.benefits.map((benefit, index) => <div key={benefit}><span>{String(index + 1).padStart(2, "0")}</span><p>{benefit}</p></div>)}</div></div></section>
    <section className="certification-split guide-shell"><div><p className="guide-kicker">Who it suits</p><h2>Designed around operating context, not company size.</h2><ul>{item.suitableFor.map((value) => <li key={value}><Check />{value}</li>)}</ul></div><div><p className="guide-kicker">Assessment focus</p><h2>What the system needs to control.</h2><ol>{item.focusAreas.map((value, index) => <li key={value}><span>{index + 1}</span>{value}</li>)}</ol></div></section>
    <section className="readiness-section"><div className="guide-shell readiness-grid"><div><ClipboardCheck /><p className="guide-kicker">Readiness evidence</p><h2>Before requesting assessment</h2><p>This is a practical starting list, not a substitute for the applicable standard or scheme rules.</p></div><ul>{item.readiness.map((value) => <li key={value}><Check /><span>{value}</span></li>)}</ul></div></section>
    <section className="pathway-section guide-shell"><div className="certification-section-head"><p className="guide-kicker">Certification pathway</p><h2>From defined scope to maintained certificate</h2></div><ol>{[["01","Application and scope","Confirm the organization, sites, activities and standard to be assessed."],["02","Readiness and assessment","Review documented arrangements and evidence that the system operates in practice."],["03","Decision and issue","Close applicable findings before an independent certification decision and issue."],["04","Surveillance and renewal","Maintain the system, complete surveillance activities and renew within the certification cycle."]].map(([number,title,text]) => <li key={number}><span>{number}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
    {related.length ? <section className="related-section"><div className="guide-shell"><div className="certification-section-head"><p className="guide-kicker">Related guides</p><h2>Standards often work together.</h2></div><div>{related.map((relatedItem) => <Link href={`/certifications/${relatedItem.slug}`} key={relatedItem.slug}><span>{relatedItem.code}</span><strong>{relatedItem.name}</strong><ArrowRight /></Link>)}</div></div></section> : null}
    <section className="detail-closing"><div className="guide-shell"><div><p className="guide-kicker">Define your certification record</p><h2>Tell us what your organization does and what the certificate should cover.</h2></div><Button asChild size="lg"><Link href={`/enquire?certification=${encodeURIComponent(item.code)}`}>Start enquiry <ArrowRight /></Link></Button></div></section><SiteFooter />
  </main>;
}
